--- 
- name: Setup Apache Tomcat and Deploy War files
  hosts: all
  become: yes
  vars: 
    tomcat_user: tomcat
    tomcat_group: tomcat
    war_file: my-webapp.war
    war_deploy_dir: /usr/share/tomcat9/webapps

  tasks:  
    - name: Install Java and Tomcat9
      yum: 
        name: 
          - java-17-amazon-corretto-devel
          - tomcat9
          - tomcat9-webapps
          - tomcat9-admin-webapps
        state: present

    - name: Ensure Tomcat is enable and started
      service: name=tomcat9 state=started enabled=true

    - name: Copy War file to tomcat wabapps directory
      copy: 
        src: "/home/abc/{{ war_file }}"
        dest: "{{ war_deploy_dir }}"
        mode: '0644'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Restart Tomcat to deploye the war files
      service: name=tomcat9 state=restarted

    - name: Ensure Tomcat is running
      systemd: 
        name: tomcat9
        state: started

        